INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (1, 'Материнская карта', '1', 5);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (2, 'Звуковая карта', null, 3);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (3, 'Процессор', '1', 6);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (4, 'Подсветка корпуса', null, 3);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (5, 'HDD диск', null, 1);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (6, 'Корпус', '1', 7);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (7, 'Память', '1', 2);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (8, 'SSD диска', '1', 10);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (9, 'Видеокарта', null, 4);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (10, 'Монитор', '1', 5);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (11, 'Наушники', null, 12);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (12, 'Клавиатура', '1', 5);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (13, 'Флеш-карта', null, 100);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (14, 'Мышка', '1', 50);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (15, 'Конденсатор', null, 100);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (16, 'Паяльник', null, 2);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (17, 'Коврик для мышки', null, 50);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (18, 'Пленка для монитора', null, 20);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (19, 'Зарядное уст-во', null, 50);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (20, 'Микрофон', '1', 40);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (21, 'Ручка', null, 50);