INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (1, '����������� �����', '1', 5);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (2, '�������� �����', null, 3);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (3, '���������', '1', 6);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (4, '��������� �������', null, 3);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (5, 'HDD ����', null, 1);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (6, '������', '1', 7);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (7, '������', '1', 2);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (8, 'SSD �����', '1', 10);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (9, '����������', null, 4);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (10, '�������', '1', 5);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (11, '��������', null, 12);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (12, '����������', '1', 5);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (13, '����-�����', null, 100);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (14, '�����', '1', 50);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (15, '�����������', null, 100);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (16, '��������', null, 2);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (17, '������ ��� �����', null, 50);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (18, '������ ��� ��������', null, 20);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (19, '�������� ���-��', null, 50);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (20, '��������', '1', 40);
INSERT INTO test.part (id, computer_part, isneeded, quantity) VALUES (21, '�����', null, 50);